#!/usr/bin/env python3
"""
Count exact features generated by FeatureStore + create_advanced_features.
"""

import sys
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
sys.path.append(str(Path(__file__).parent))

import pandas as pd
import numpy as np

from core.utils import load_config
from core.bybit_rest import BybitRESTClient
from core.data import DataManager
from core.features import FeatureStore

# Load config
config = load_config('config.json')

# Initialize
rest_client = BybitRESTClient(
    api_key=config['bybit_api_key'],
    api_secret=config['bybit_api_secret'],
    testnet=config['bybit_testnet']
)

data_manager = DataManager(rest_client)
feature_store = FeatureStore(config)

print("\n" + "=" * 80)
print("🔍 CONTAGEM EXATA DE FEATURES")
print("=" * 80)
print()

# Download small sample
print("📥 Baixando dados...")
df = data_manager.get_data(
    symbol='BTCUSDT',
    interval='15m',
    days_back=3,
    use_cache=False
)
print(f"✅ {len(df)} candles baixados")
print()

# Step 1: Initial columns (OHLCV)
initial_cols = set(df.columns)
print(f"📊 INICIAL (OHLCV): {len(initial_cols)} colunas")
for col in sorted(initial_cols):
    print(f"   • {col}")
print()

# Step 2: After FeatureStore
df = feature_store.build_features(df, normalize=False)
after_fs = set(df.columns)
added_by_fs = after_fs - initial_cols

print(f"📊 DEPOIS FeatureStore: {len(after_fs)} colunas ({len(added_by_fs)} adicionadas)")
print()
print("Features adicionadas pelo FeatureStore:")
for col in sorted(added_by_fs):
    print(f"   • {col}")
print()

# Step 3: After create_advanced_features
def create_advanced_features(df: pd.DataFrame) -> pd.DataFrame:
    """Add MASTER TRADER advanced features."""
    df_features = df.copy()

    # Multi-period momentum
    for period in [3, 5, 8, 13, 21]:
        df_features[f'momentum_{period}'] = df_features['close'].pct_change(period) * 100
        df_features[f'volume_ratio_{period}'] = df_features['volume'] / df_features['volume'].rolling(period).mean()

    # Trend strength
    if 'ema50' in df_features.columns and 'ema200' in df_features.columns:
        df_features['trend_strength'] = (df_features['ema50'] - df_features['ema200']) / df_features['ema200'] * 100

    # Volatility regimes
    if 'atr' in df_features.columns:
        df_features['volatility_regime'] = (df_features['atr'] / df_features['atr'].rolling(50).mean())

    # Price position
    df_features['price_position'] = (
        (df_features['close'] - df_features['low'].rolling(20).min()) /
        (df_features['high'].rolling(20).max() - df_features['low'].rolling(20).min())
    ).fillna(0.5)

    # Volume momentum
    df_features['volume_momentum'] = df_features['volume'].pct_change(5)

    # Acceleration
    df_features['price_acceleration'] = df_features['close'].diff(2) - df_features['close'].diff(1)

    return df_features

df = create_advanced_features(df)
after_advanced = set(df.columns)
added_by_advanced = after_advanced - after_fs

print(f"📊 DEPOIS create_advanced_features: {len(after_advanced)} colunas ({len(added_by_advanced)} adicionadas)")
print()
print("Features adicionadas por create_advanced_features:")
for col in sorted(added_by_advanced):
    print(f"   • {col}")
print()

# Step 4: Remove excluded columns (like training does)
exclude_cols = ['close', 'high', 'low', 'open', 'volume', 'target', 'vote_confidence', 'trend', 'structure']
feature_cols = [col for col in df.columns if col not in exclude_cols]

# Remove object types
object_cols = df[feature_cols].select_dtypes(include=['object']).columns.tolist()
if object_cols:
    print(f"🗑️  Removendo {len(object_cols)} colunas tipo object:")
    for col in object_cols:
        print(f"   • {col}")
    feature_cols = [col for col in feature_cols if col not in object_cols]
    print()

print("=" * 80)
print(f"✅ FEATURES FINAIS: {len(feature_cols)} (depois de excluir OHLCV e object)")
print("=" * 80)
print()

# Show breakdown
print("📋 BREAKDOWN:")
print(f"   OHLCV:                5 colunas (excluídas)")
print(f"   FeatureStore:         {len(added_by_fs)} colunas")
print(f"   Advanced features:    {len(added_by_advanced)} colunas")
print(f"   Object columns:       {len(object_cols)} colunas (excluídas)")
print(f"   ────────────────────────────")
print(f"   TOTAL FINAL:          {len(feature_cols)} features ✅")
print()

# Compare with model expectation
print("=" * 80)
print(f"📊 COMPARAÇÃO:")
print(f"   Modelo espera:  73 features")
print(f"   Bot gera:       {len(feature_cols)} features")
print(f"   Diferença:      {abs(len(feature_cols) - 73)} features")
if len(feature_cols) == 73:
    print(f"   Status:         ✅ PERFEITO!")
elif len(feature_cols) > 73:
    print(f"   Status:         ⚠️  {len(feature_cols) - 73} features EXTRAS")
else:
    print(f"   Status:         ❌ {73 - len(feature_cols)} features FALTANDO")
print("=" * 80)
print()

# Save full list
with open('/tmp/bot_features_final.txt', 'w') as f:
    f.write(f"# Features geradas pelo bot ({len(feature_cols)} total)\n\n")
    for i, col in enumerate(sorted(feature_cols), 1):
        f.write(f"{i:3d}. {col}\n")

print(f"📝 Lista completa salva em: /tmp/bot_features_final.txt")
print()
